package com.encer.splitwise.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.encer.splitwise.data.preferences.AppLanguage
import com.encer.splitwise.core.common.MessageKey

data class AppStrings(
    val appTitle: String,
    val authHeroTitle: String,
    val authHeroSubtitle: String,
    val authLoginTitle: String,
    val authLoginSubtitle: String,
    val authRegisterTitle: String,
    val authRegisterSubtitle: String,
    val nameLabel: String,
    val usernameLabel: String,
    val passwordLabel: String,
    val loginAction: String,
    val registerAction: String,
    val continueOfflineAction: String,
    val noAccountPrompt: String,
    val hasAccountPrompt: String,
    val authFailed: String,
    val authLoginFailed: String,
    val authRegisterFailed: String,
    val authNameRequired: String,
    val authUsernameRequired: String,
    val authPasswordRequired: String,
    val authInvalidCredentials: String,
    val authUsernameTaken: String,
    val authNetworkError: String,
    val authLoginLoading: String,
    val authRegisterLoading: String,
    val homeTab: String,
    val settingsTab: String,
    val addGroup: String,
    val newGroupTitle: String,
    val editGroupTitle: String,
    val groupPlaceholder: String,
    val createGroup: String,
    val save: String,
    val cancel: String,
    val leaveGroup: String,
    val deleteGroupForEveryone: String,
    val groupActionDialogSubtitle: String,
    val groupDeleteConfirmMessage: String,
    val groupLeaveMessage: String,
    val needSecondMemberMessage: String,
    val updateNow: String,
    val updateLater: String,
    val updateRequiredTitle: String,
    val updateAvailableTitle: String,
    val updateDefaultMessage: String,
    val groupsSectionTitle: String,
    val noGroupsTitle: String,
    val noGroupsSubtitle: String,
    val searchGroupsLabel: String,
    val noSearchResultsTitle: String,
    val noSearchResultsSubtitle: String,
    val homeHeroTitle: String,
    val homeHeroSubtitle: String,
    val groupFallbackTitle: String,
    val groupOverviewTitle: String,
    val groupOverviewSubtitle: String,
    val totalExpenseLabel: String,
    val membersLabel: String,
    val settlementsLabel: String,
    val openBalancesLabel: String,
    val membersAction: String,
    val newExpenseAction: String,
    val addSettlementAction: String,
    val balancesAction: String,
    val recentExpensesTitle: String,
    val recentSettlementsTitle: String,
    val noExpensesTitle: String,
    val noExpensesSubtitle: String,
    val noSettlementsTitle: String,
    val noSettlementsSubtitle: String,
    val membersOfGroupPrefix: String,
    val invitesTitle: String,
    val noInvitesTitle: String,
    val noInvitesSubtitle: String,
    val acceptInvite: String,
    val rejectInvite: String,
    val pendingInviteLabel: String,
    val addMember: String,
    val editMember: String,
    val memberPlaceholder: String,
    val saveMember: String,
    val deleteMemberTitle: String,
    val deleteMemberSubtitle: String,
    val noMembersTitle: String,
    val noMembersSubtitle: String,
    val invalidUsernameSyncTitle: String,
    val invalidUsernameSyncSubtitle: String,
    val addExpenseTitle: String,
    val editExpenseTitle: String,
    val expenseHeroTitle: String,
    val expenseHeroSubtitle: String,
    val expenseTitleLabel: String,
    val expenseNoteLabel: String,
    val totalAmountLabel: String,
    val equalSplitLabel: String,
    val exactSplitLabel: String,
    val membersAndPayersTitle: String,
    val saveExpense: String,
    val saveExpenseChanges: String,
    val addSettlementTitle: String,
    val editSettlementTitle: String,
    val settlementHeroTitle: String,
    val settlementHeroSubtitle: String,
    val payerLabel: String,
    val receiverLabel: String,
    val settlementParticipantsTitle: String,
    val settlementAmountLabel: String,
    val noteLabel: String,
    val saveSettlement: String,
    val saveSettlementChanges: String,
    val suggestedSettlementLabel: String,
    val fillSuggestedAmountLabel: String,
    val selectedPayerLabel: String,
    val selectedReceiverLabel: String,
    val balancesPrefix: String,
    val optimizePaymentsTitle: String,
    val optimizePaymentsSubtitle: String,
    val memberBalanceTitle: String,
    val memberBalanceSubtitle: String,
    val suggestedPaymentsTitle: String,
    val allSettledTitle: String,
    val allSettledSubtitle: String,
    val expenseDetailsFallback: String,
    val expenseNotFound: String,
    val noDescription: String,
    val totalAmountStat: String,
    val splitMethodStat: String,
    val dateStat: String,
    val peopleCountStat: String,
    val payersTitle: String,
    val sharesTitle: String,
    val paidHowMuchLabel: String,
    val paidHowMuchHint: String,
    val payFullAmountLabel: String,
    val clearAmountLabel: String,
    val baseShareLabel: String,
    val shareAmountHint: String,
    val equalBaseShareLabel: String,
    val expenseSummaryTitle: String,
    val enteredPayersTitle: String,
    val remainingPayersTitle: String,
    val enteredSharesTitle: String,
    val remainingSharesTitle: String,
    val finalSharesTitle: String,
    val payerRemainingHintLabel: String,
    val shareRemainingHintLabel: String,
    val taxToggleTitle: String,
    val taxToggleSubtitle: String,
    val taxPercentLabel: String,
    val taxAmountLabel: String,
    val taxBreakdownTitle: String,
    val baseAmountLabel: String,
    val taxShareLabel: String,
    val serviceChargeShareLabel: String,
    val finalShareLabel: String,
    val showDetailsLabel: String,
    val hideDetailsLabel: String,
    val serviceChargesTitle: String,
    val serviceChargesSubtitle: String,
    val addServiceChargeLabel: String,
    val serviceChargeNameLabel: String,
    val serviceChargeAmountLabel: String,
    val serviceChargeMembersLabel: String,
    val serviceChargeHint: String,
    val serviceChargesTotalLabel: String,
    val completeExpenseForm: String,
    val calculatorTitle: String,
    val calculatorExpressionLabel: String,
    val calculatorInvalidExpression: String,
    val calculatorUseAction: String,
    val creditorLabel: String,
    val debtorLabel: String,
    val settledLabel: String,
    val paidStat: String,
    val owedStat: String,
    val netStat: String,
    val edit: String,
    val delete: String,
    val back: String,
    val settingsHeroTitle: String,
    val settingsHeroSubtitle: String,
    val accountTitle: String,
    val accountSubtitleGuest: String,
    val accountSubtitleSignedIn: String,
    val syncTitle: String,
    val syncSubtitle: String,
    val syncOnline: String,
    val syncOffline: String,
    val syncLoginRequired: String,
    val syncNow: String,
    val syncInProgress: String,
    val lastSyncPrefix: String,
    val notSyncedYet: String,
    val syncConnectionIssue: String,
    val syncServerIssue: String,
    val logoutLabel: String,
    val signInLabel: String,
    val languageTitle: String,
    val languageSubtitle: String,
    val themeTitle: String,
    val themeSubtitle: String,
    val persianLabel: String,
    val englishLabel: String,
    val lightLabel: String,
    val darkLabel: String,
) {
    fun memberSince(date: String): String =
        if (appTitle == "Splitwise") "Member since $date" else "عضو از $date"

    fun deleteMemberDialogTitle(username: String): String =
        if (appTitle == "Splitwise") "$deleteMemberTitle @$username?" else "$deleteMemberTitle @$username؟"

    fun paymentSuggestion(from: String, to: String): String =
        if (appTitle == "Splitwise") "$from should pay $to" else "$from باید به $to پرداخت کند"

    fun payersSummary(names: String): String =
        if (appTitle == "Splitwise") "Payers: $names" else "پرداخت‌کننده‌ها: $names"

    fun settlementSummary(from: String, to: String): String =
        if (appTitle == "Splitwise") "$from paid $to" else "$from به $to"

    fun settlementRecommendation(from: String, to: String, amount: String): String =
        if (appTitle == "Splitwise") "$from should pay $to $amount." else "$from باید $amount به $to پرداخت کند."

    fun membersOfGroup(groupName: String): String =
        if (appTitle == "Splitwise") "$membersOfGroupPrefix $groupName" else "$membersOfGroupPrefix $groupName"

    fun balancesOfGroup(groupName: String): String =
        if (appTitle == "Splitwise") "$balancesPrefix $groupName" else "$balancesPrefix $groupName"

    fun memberFallback(memberId: String): String =
        if (appTitle == "Splitwise") "Member $memberId" else "کاربر $memberId"

    fun lastSyncLabel(value: String): String =
        if (appTitle == "Splitwise") "$lastSyncPrefix $value" else "$lastSyncPrefix $value"

    fun groupActionDialogTitle(groupName: String): String =
        if (appTitle == "Splitwise") "Manage $groupName" else "مدیریت $groupName"

    fun payerRemainingHint(amount: String): String =
        if (appTitle == "Splitwise") "$payerRemainingHintLabel: $amount" else "$payerRemainingHintLabel: $amount"

    fun shareRemainingHint(amount: String): String =
        if (appTitle == "Splitwise") "$shareRemainingHintLabel: $amount" else "$shareRemainingHintLabel: $amount"

    fun applyRemainingPayer(amount: String): String =
        if (appTitle == "Splitwise") "Fill remaining payer $amount" else "باقی‌مانده پرداخت $amount"

    fun applyRemainingShare(amount: String): String =
        if (appTitle == "Splitwise") "Fill remaining share $amount" else "باقی‌مانده سهم $amount"

    fun applyEqualRemainingShare(amount: String): String =
        if (appTitle == "Splitwise") "Split remaining equally $amount" else "تقسیم مساوی باقیمانده $amount"

    fun payerOverflowMessage(amount: String): String =
        if (appTitle == "Splitwise") "Payers exceed total by $amount." else "جمع پرداخت‌ها $amount از کل بیشتر شده است."

    fun shareOverflowMessage(amount: String): String =
        if (appTitle == "Splitwise") "Shares exceed target by $amount." else "جمع سهم‌ها $amount از مقدار هدف بیشتر شده است."

    fun finalShareWithTax(amount: String): String =
        if (appTitle == "Splitwise") "Final share with tax: $amount" else "سهم نهایی با مالیات: $amount"

    fun serviceChargePreview(memberCount: Int, perMemberAmount: String): String =
        if (appTitle == "Splitwise") "For $memberCount members, $perMemberAmount each." else "برای $memberCount نفر، سهم هر نفر $perMemberAmount است."

    fun serviceChargeItemTitle(index: Int): String =
        if (appTitle == "Splitwise") "Extra service $index" else "سرویس اضافه $index"

    fun expenseFormTitle(isEdit: Boolean): String = if (isEdit) editExpenseTitle else addExpenseTitle
    fun expenseFormAction(isEdit: Boolean): String = if (isEdit) saveExpenseChanges else saveExpense
    fun settlementFormTitle(isEdit: Boolean): String = if (isEdit) editSettlementTitle else addSettlementTitle
    fun settlementFormAction(isEdit: Boolean): String = if (isEdit) saveSettlementChanges else saveSettlement
    fun splitTypeLabel(isEqual: Boolean): String = if (isEqual) equalSplitLabel else exactSplitLabel
    fun balanceState(net: Int): String = when {
        net > 0 -> creditorLabel
        net < 0 -> debtorLabel
        else -> settledLabel
    }

    fun message(key: MessageKey?): String? = when (key) {
        null -> null
        MessageKey.EXPENSE_TOTAL_POSITIVE -> if (appTitle == "Splitwise") "Total amount must be greater than zero." else "مبلغ کل باید بیشتر از صفر باشد."
        MessageKey.EXPENSE_AT_LEAST_ONE_PAYER -> if (appTitle == "Splitwise") "At least one payer is required." else "حداقل یک پرداخت‌کننده لازم است."
        MessageKey.EXPENSE_AT_LEAST_ONE_SHARE -> if (appTitle == "Splitwise") "Select at least one participant." else "حداقل یک نفر باید در تقسیم حضور داشته باشد."
        MessageKey.EXPENSE_NEGATIVE_VALUES -> if (appTitle == "Splitwise") "Negative amounts are not allowed." else "مقادیر منفی مجاز نیستند."
        MessageKey.EXPENSE_PAYER_TOTAL_MISMATCH -> if (appTitle == "Splitwise") "Payer totals must match the full amount." else "جمع پرداخت‌کننده‌ها باید با مبلغ کل برابر باشد."
        MessageKey.EXPENSE_SHARE_TOTAL_MISMATCH -> if (appTitle == "Splitwise") "Shares must match the full amount." else "جمع سهم‌ها باید با مبلغ کل برابر باشد."
        MessageKey.EXPENSE_TITLE_REQUIRED -> if (appTitle == "Splitwise") "Enter an expense title." else "عنوان خرج را وارد کنید."
        MessageKey.EXPENSE_AMOUNT_TOO_LARGE -> if (appTitle == "Splitwise") "Entered amount is too large." else "عدد واردشده بیش از حد بزرگ است."
        MessageKey.EXPENSE_TAX_PERCENT_INVALID -> if (appTitle == "Splitwise") "Tax percent must be between 0 and 100." else "درصد مالیات باید بین صفر تا ۱۰۰ باشد."
        MessageKey.EXPENSE_SERVICE_CHARGE_INVALID -> if (appTitle == "Splitwise") "Each extra service needs an amount and at least one member." else "هر سرویس اضافه باید مبلغ و حداقل یک عضو داشته باشد."
        MessageKey.EXPENSE_SAVED -> if (appTitle == "Splitwise") "Expense saved." else "خرج ذخیره شد."
        MessageKey.SETTLEMENT_SELECT_TWO_MEMBERS -> if (appTitle == "Splitwise") "Select two members." else "دو نفر را انتخاب کنید."
        MessageKey.SETTLEMENT_MEMBERS_MUST_DIFFER -> if (appTitle == "Splitwise") "Payer and receiver must be different." else "پرداخت‌کننده و دریافت‌کننده باید متفاوت باشند."
        MessageKey.SETTLEMENT_AMOUNT_POSITIVE -> if (appTitle == "Splitwise") "Settlement amount must be greater than zero." else "مبلغ تسویه باید بیشتر از صفر باشد."
        MessageKey.SETTLEMENT_AMOUNT_TOO_LARGE -> if (appTitle == "Splitwise") "Settlement amount is too large." else "مبلغ تسویه بیش از حد بزرگ است."
        MessageKey.SETTLEMENT_SAVED -> if (appTitle == "Splitwise") "Settlement saved." else "تسویه ذخیره شد."
    }
}

private val faStrings = AppStrings(
    appTitle = "دنگینو",
    authHeroTitle = "همگام با اکانت، آماده برای آفلاین",
    authHeroSubtitle = "وارد شو تا داده‌ها با سرور سینک شوند، یا بدون حساب به‌صورت محلی ادامه بده.",
    authLoginTitle = "ورود به حساب",
    authLoginSubtitle = "برای همگام‌سازی داده‌ها، با حساب خودت وارد شو.",
    authRegisterTitle = "ساخت حساب جدید",
    authRegisterSubtitle = "یک حساب بساز تا بعداً داده‌ها بین دستگاه‌ها همگام شوند.",
    nameLabel = "نام",
    usernameLabel = "نام کاربری",
    passwordLabel = "رمز عبور",
    loginAction = "ورود",
    registerAction = "ثبت‌نام",
    continueOfflineAction = "ادامه در حالت آفلاین",
    noAccountPrompt = "حساب نداری؟ ثبت‌نام کن",
    hasAccountPrompt = "حساب داری؟ وارد شو",
    authFailed = "ورود یا ثبت‌نام انجام نشد.",
    authLoginFailed = "ورود انجام نشد.",
    authRegisterFailed = "ثبت‌نام انجام نشد.",
    authNameRequired = "نام را وارد کن.",
    authUsernameRequired = "نام کاربری را وارد کن.",
    authPasswordRequired = "رمز عبور را وارد کن.",
    authInvalidCredentials = "نام کاربری یا رمز عبور درست نیست.",
    authUsernameTaken = "این نام کاربری قبلاً استفاده شده است.",
    authNetworkError = "اتصال به سرور برقرار نشد. اینترنت را بررسی کن و دوباره تلاش کن.",
    authLoginLoading = "در حال ورود...",
    authRegisterLoading = "در حال ساخت حساب...",
    homeTab = "خانه",
    settingsTab = "تنظیمات",
    addGroup = "افزودن گروه",
    newGroupTitle = "گروه جدید",
    editGroupTitle = "ویرایش گروه",
    groupPlaceholder = "مثلا سفر شمال",
    createGroup = "ساخت گروه",
    save = "ذخیره",
    cancel = "انصراف",
    leaveGroup = "خروج از گروه",
    deleteGroupForEveryone = "حذف برای همه",
    groupActionDialogSubtitle = "یکی از این دو کار را انتخاب کن.",
    groupDeleteConfirmMessage = "گروه برای همه پاک می‌شود.",
    groupLeaveMessage = "فقط تو از گروه خارج می‌شوی.",
    needSecondMemberMessage = "برای ثبت خرج و تسویه، اول حداقل یک عضو دیگر به گروه اضافه کن.",
    updateNow = "به‌روزرسانی",
    updateLater = "بعداً",
    updateRequiredTitle = "به‌روزرسانی اجباری",
    updateAvailableTitle = "نسخه جدید آماده است",
    updateDefaultMessage = "برای ادامه، نسخه جدید برنامه را نصب کن.",
    groupsSectionTitle = "گروه‌ها",
    noGroupsTitle = "هنوز گروهی نداری",
    noGroupsSubtitle = "از دکمه بالا یک گروه جدید بساز.",
    searchGroupsLabel = "جستجوی گروه",
    noSearchResultsTitle = "گروهی پیدا نشد",
    noSearchResultsSubtitle = "عبارت جستجو را تغییر بده و دوباره امتحان کن.",
    homeHeroTitle = "خرج‌ها را آفلاین جمع کن",
    homeHeroSubtitle = "برای هر سفر یا جمع، گروه بساز، اعضا را اضافه کن و بدهی‌ها را با حالت simplify ببین.",
    groupFallbackTitle = "گروه",
    groupOverviewTitle = "وضعیت کلی گروه",
    groupOverviewSubtitle = "خرج‌ها، اعضا، تسویه‌ها و مانده‌های باز را از همین‌جا کنترل کن.",
    totalExpenseLabel = "کل خرج",
    membersLabel = "اعضا",
    settlementsLabel = "تسویه‌ها",
    openBalancesLabel = "مانده باز",
    membersAction = "اعضا",
    newExpenseAction = "خرج جدید",
    addSettlementAction = "ثبت تسویه",
    balancesAction = "مانده‌ها",
    recentExpensesTitle = "آخرین خرج‌ها",
    recentSettlementsTitle = "تسویه‌های اخیر",
    noExpensesTitle = "خرجی ثبت نشده",
    noExpensesSubtitle = "اولین خرج گروه را ثبت کن تا مانده‌ها محاسبه شوند.",
    noSettlementsTitle = "تسویه‌ای ثبت نشده",
    noSettlementsSubtitle = "وقتی کسی بدهی‌اش را داد، از اینجا ثبتش کن.",
    membersOfGroupPrefix = "اعضای",
    invitesTitle = "دعوت‌نامه‌ها",
    noInvitesTitle = "دعوت‌نامه‌ای نداری",
    noInvitesSubtitle = "وقتی کسی تو را به گروهی دعوت کند، اینجا دیده می‌شود.",
    acceptInvite = "قبول",
    rejectInvite = "رد",
    pendingInviteLabel = "در انتظار تایید",
    addMember = "افزودن عضو",
    editMember = "ویرایش عضو",
    memberPlaceholder = "نام کاربری عضو",
    saveMember = "ثبت عضو",
    deleteMemberTitle = "حذف عضو",
    deleteMemberSubtitle = "این عضو از گروه حذف می‌شود. اگر خرج یا تسویه‌ای به او وصل باشد، قبل از حذف بررسی‌اش کن.",
    noMembersTitle = "هیچ عضوی ثبت نشده",
    noMembersSubtitle = "برای ثبت خرج حداقل یک عضو نیاز داری.",
    invalidUsernameSyncTitle = "همگام‌سازی به خاطر نام کاربری نامعتبر متوقف شد",
    invalidUsernameSyncSubtitle = "این نام‌های کاربری روی سرور وجود ندارند. آن‌ها را ویرایش کن و دوباره سینک بزن.",
    addExpenseTitle = "خرج جدید",
    editExpenseTitle = "ویرایش خرج",
    expenseHeroTitle = "خرج را دقیق ثبت کن",
    expenseHeroSubtitle = "می‌توانی مشخص کنی چه کسی پرداخت کرده و سهم هر نفر چقدر بوده.",
    expenseTitleLabel = "عنوان خرج",
    expenseNoteLabel = "توضیح",
    totalAmountLabel = "مبلغ کل (تومان)",
    equalSplitLabel = "تقسیم مساوی",
    exactSplitLabel = "مبلغ دقیق",
    membersAndPayersTitle = "اعضا و پرداخت‌کننده‌ها",
    saveExpense = "ثبت خرج",
    saveExpenseChanges = "ذخیره تغییرات",
    addSettlementTitle = "ثبت تسویه",
    editSettlementTitle = "ویرایش تسویه",
    settlementHeroTitle = "تسویه واقعی را ثبت کن",
    settlementHeroSubtitle = "وقتی یکی بدهی‌اش را به دیگری پرداخت کرد، اینجا ثبتش کن تا مانده‌ها اصلاح شوند.",
    payerLabel = "پرداخت‌کننده",
    receiverLabel = "دریافت‌کننده",
    settlementParticipantsTitle = "بین چه کسانی؟",
    settlementAmountLabel = "مبلغ تسویه",
    noteLabel = "یادداشت",
    saveSettlement = "ثبت تسویه",
    saveSettlementChanges = "ذخیره تغییرات",
    suggestedSettlementLabel = "مبلغ پیشنهادی",
    fillSuggestedAmountLabel = "پر کردن مبلغ پیشنهادی",
    selectedPayerLabel = "پرداخت‌کننده انتخاب‌شده",
    selectedReceiverLabel = "دریافت‌کننده انتخاب‌شده",
    balancesPrefix = "مانده‌های",
    optimizePaymentsTitle = "حالت پرداخت بهینه",
    optimizePaymentsSubtitle = "کمترین تعداد پرداخت پیشنهادی را نشان می‌دهد.",
    memberBalanceTitle = "مانده هر نفر",
    memberBalanceSubtitle = "وضعیت این عضو در گروه",
    suggestedPaymentsTitle = "پرداخت‌های پیشنهادی",
    allSettledTitle = "همه‌چیز تسویه است",
    allSettledSubtitle = "در این گروه پرداخت باز باقی نمانده.",
    expenseDetailsFallback = "جزئیات خرج",
    expenseNotFound = "خرج پیدا نشد.",
    noDescription = "بدون توضیح",
    totalAmountStat = "مبلغ کل",
    splitMethodStat = "روش تقسیم",
    dateStat = "تاریخ",
    peopleCountStat = "تعداد افراد",
    payersTitle = "پرداخت‌کننده‌ها",
    sharesTitle = "سهم افراد",
    paidHowMuchLabel = "چقدر پرداخت کرده؟",
    paidHowMuchHint = "این عضو از جیب خودش چقدر داده؟",
    payFullAmountLabel = "کل مبلغ با این نفر",
    clearAmountLabel = "پاک کردن مبلغ",
    baseShareLabel = "سهم پایه این نفر",
    shareAmountHint = "از کل خرج، این نفر چقدر بدهکار است؟",
    equalBaseShareLabel = "سهم پایه مساوی",
    expenseSummaryTitle = "خلاصه زنده خرج",
    enteredPayersTitle = "جمع پرداخت‌ها",
    remainingPayersTitle = "باقی‌مانده پرداخت",
    enteredSharesTitle = "جمع سهم‌ها",
    remainingSharesTitle = "باقی‌مانده سهم",
    finalSharesTitle = "جمع سهم نهایی",
    payerRemainingHintLabel = "باقی‌مانده برای پرداخت",
    shareRemainingHintLabel = "باقی‌مانده برای سهم",
    taxToggleTitle = "مالیات یا سرویس اضافه دارد",
    taxToggleSubtitle = "برای رستوران، سرویس، مالیات یا درصد اضافه.",
    taxPercentLabel = "درصد مالیات",
    taxAmountLabel = "مبلغ مالیات",
    taxBreakdownTitle = "جزئیات مالیات",
    baseAmountLabel = "مبلغ پایه",
    taxShareLabel = "مالیات این نفر",
    serviceChargeShareLabel = "سرویس اضافه این نفر",
    finalShareLabel = "سهم نهایی",
    showDetailsLabel = "جزئیات",
    hideDetailsLabel = "بستن جزئیات",
    serviceChargesTitle = "سرویس‌های اضافه",
    serviceChargesSubtitle = "برای هزینه‌های ثابت مثل سرویس میز یا خدمات ویژه.",
    addServiceChargeLabel = "افزودن سرویس",
    serviceChargeNameLabel = "عنوان سرویس",
    serviceChargeAmountLabel = "مبلغ سرویس",
    serviceChargeMembersLabel = "برای چه افرادی؟",
    serviceChargeHint = "برای این سرویس مبلغ و اعضای مرتبط را انتخاب کن.",
    serviceChargesTotalLabel = "جمع سرویس‌های اضافه",
    completeExpenseForm = "تکمیل فرم",
    calculatorTitle = "ماشین‌حساب",
    calculatorExpressionLabel = "عبارت",
    calculatorInvalidExpression = "عبارت معتبر نیست",
    calculatorUseAction = "استفاده",
    creditorLabel = "طلبکار",
    debtorLabel = "بدهکار",
    settledLabel = "تسویه",
    paidStat = "پرداخت",
    owedStat = "سهم",
    netStat = "خالص",
    edit = "ویرایش",
    delete = "حذف",
    back = "بازگشت",
    settingsHeroTitle = "ظاهر و زبان اپ را تنظیم کن",
    settingsHeroSubtitle = "از اینجا بین فارسی و انگلیسی و بین تم روشن و تیره جابه‌جا شو.",
    accountTitle = "حساب",
    accountSubtitleGuest = "فعلا در حالت مهمان هستی. برای سینک، وارد حساب شو.",
    accountSubtitleSignedIn = "هویت فعلی که داده‌ها با آن همگام می‌شوند.",
    syncTitle = "همگام‌سازی",
    syncSubtitle = "وضعیت اتصال، آخرین سینک و همگام‌سازی دستی را از اینجا ببین.",
    syncOnline = "آنلاین",
    syncOffline = "آفلاین",
    syncLoginRequired = "برای همگام‌سازی، وارد حساب شو.",
    syncNow = "سینک لحظه‌ای",
    syncInProgress = "در حال همگام‌سازی...",
    lastSyncPrefix = "آخرین سینک:",
    notSyncedYet = "هنوز سینک نشده",
    syncConnectionIssue = "اتصال اینترنت برقرار نیست. بعد از وصل شدن دوباره امتحان کن.",
    syncServerIssue = "همگام‌سازی انجام نشد. کمی بعد دوباره تلاش کن.",
    logoutLabel = "خروج از حساب",
    signInLabel = "ورود به حساب",
    languageTitle = "زبان",
    languageSubtitle = "زبان نوشته‌ها و جهت چیدمان اپ را انتخاب کن.",
    themeTitle = "تم",
    themeSubtitle = "ظاهر روشن یا تیره را بر اساس سلیقه‌ات انتخاب کن.",
    persianLabel = "فارسی",
    englishLabel = "English",
    lightLabel = "روشن",
    darkLabel = "تیره",
)

private val enStrings = AppStrings(
    appTitle = "Splitwise",
    authHeroTitle = "Sign in for sync, keep working offline",
    authHeroSubtitle = "Use your account to sync with the server, or continue locally without signing in.",
    authLoginTitle = "Sign in",
    authLoginSubtitle = "Use your account to sync data across sessions.",
    authRegisterTitle = "Create account",
    authRegisterSubtitle = "Create an account now so your data can sync later.",
    nameLabel = "Name",
    usernameLabel = "Username",
    passwordLabel = "Password",
    loginAction = "Sign in",
    registerAction = "Create account",
    continueOfflineAction = "Continue offline",
    noAccountPrompt = "No account? Create one",
    hasAccountPrompt = "Already have an account? Sign in",
    authFailed = "Authentication failed.",
    authLoginFailed = "Sign in failed.",
    authRegisterFailed = "Registration failed.",
    authNameRequired = "Enter your name.",
    authUsernameRequired = "Enter a username.",
    authPasswordRequired = "Enter a password.",
    authInvalidCredentials = "Username or password is incorrect.",
    authUsernameTaken = "This username is already taken.",
    authNetworkError = "Could not reach the server. Check your connection and try again.",
    authLoginLoading = "Signing in...",
    authRegisterLoading = "Creating account...",
    homeTab = "Home",
    settingsTab = "Settings",
    addGroup = "Add group",
    newGroupTitle = "New group",
    editGroupTitle = "Edit group",
    groupPlaceholder = "For example: North trip",
    createGroup = "Create group",
    save = "Save",
    cancel = "Cancel",
    leaveGroup = "Leave group",
    deleteGroupForEveryone = "Delete for everyone",
    groupActionDialogSubtitle = "Choose one action.",
    groupDeleteConfirmMessage = "The group will be removed for everyone.",
    groupLeaveMessage = "Only you will leave the group.",
    needSecondMemberMessage = "Add at least one more member before creating expenses or settlements.",
    updateNow = "Update now",
    updateLater = "Later",
    updateRequiredTitle = "Update required",
    updateAvailableTitle = "New version available",
    updateDefaultMessage = "Install the latest version of the app to continue.",
    groupsSectionTitle = "Groups",
    noGroupsTitle = "No groups yet",
    noGroupsSubtitle = "Create your first group from the button above.",
    searchGroupsLabel = "Search groups",
    noSearchResultsTitle = "No matching group found",
    noSearchResultsSubtitle = "Try a different search phrase.",
    homeHeroTitle = "Track shared costs offline",
    homeHeroSubtitle = "Create a group for each trip or circle, add members, and keep debts simplified.",
    groupFallbackTitle = "Group",
    groupOverviewTitle = "Group overview",
    groupOverviewSubtitle = "Control expenses, members, settlements, and open balances from here.",
    totalExpenseLabel = "Total spent",
    membersLabel = "Members",
    settlementsLabel = "Settlements",
    openBalancesLabel = "Open balances",
    membersAction = "Members",
    newExpenseAction = "New expense",
    addSettlementAction = "Settle up",
    balancesAction = "Balances",
    recentExpensesTitle = "Recent expenses",
    recentSettlementsTitle = "Recent settlements",
    noExpensesTitle = "No expenses yet",
    noExpensesSubtitle = "Add the first expense to start calculating balances.",
    noSettlementsTitle = "No settlements yet",
    noSettlementsSubtitle = "Record a payment here whenever someone settles up.",
    membersOfGroupPrefix = "Members of",
    invitesTitle = "Invites",
    noInvitesTitle = "No pending invites",
    noInvitesSubtitle = "Incoming group invites show up here.",
    acceptInvite = "Accept",
    rejectInvite = "Reject",
    pendingInviteLabel = "Pending",
    addMember = "Add member",
    editMember = "Edit member",
    memberPlaceholder = "Member username",
    saveMember = "Save member",
    deleteMemberTitle = "Delete member",
    deleteMemberSubtitle = "This member will be removed from the group. Review any linked expenses or settlements before confirming.",
    noMembersTitle = "No members yet",
    noMembersSubtitle = "You need at least one member before adding expenses.",
    invalidUsernameSyncTitle = "Sync blocked by invalid usernames",
    invalidUsernameSyncSubtitle = "These usernames do not exist on the server. Edit them and sync again.",
    addExpenseTitle = "New expense",
    editExpenseTitle = "Edit expense",
    expenseHeroTitle = "Capture the expense clearly",
    expenseHeroSubtitle = "Specify who paid and how much each member actually owes.",
    expenseTitleLabel = "Expense title",
    expenseNoteLabel = "Note",
    totalAmountLabel = "Total amount (Toman)",
    equalSplitLabel = "Equal split",
    exactSplitLabel = "Exact amounts",
    membersAndPayersTitle = "Members and payers",
    saveExpense = "Save expense",
    saveExpenseChanges = "Save changes",
    addSettlementTitle = "New settlement",
    editSettlementTitle = "Edit settlement",
    settlementHeroTitle = "Record a real settlement",
    settlementHeroSubtitle = "When someone pays another member back, store it here so balances update.",
    payerLabel = "Payer",
    receiverLabel = "Receiver",
    settlementParticipantsTitle = "Who paid whom?",
    settlementAmountLabel = "Settlement amount",
    noteLabel = "Note",
    saveSettlement = "Save settlement",
    saveSettlementChanges = "Save changes",
    suggestedSettlementLabel = "Suggested amount",
    fillSuggestedAmountLabel = "Fill suggested amount",
    selectedPayerLabel = "Selected payer",
    selectedReceiverLabel = "Selected receiver",
    balancesPrefix = "Balances for",
    optimizePaymentsTitle = "Simplified payments",
    optimizePaymentsSubtitle = "Shows the minimum suggested number of payments.",
    memberBalanceTitle = "Each member balance",
    memberBalanceSubtitle = "This member status in group",
    suggestedPaymentsTitle = "Suggested payments",
    allSettledTitle = "Everything is settled",
    allSettledSubtitle = "There are no outstanding payments in this group.",
    expenseDetailsFallback = "Expense details",
    expenseNotFound = "Expense not found.",
    noDescription = "No description",
    totalAmountStat = "Total amount",
    splitMethodStat = "Split method",
    dateStat = "Date",
    peopleCountStat = "People",
    payersTitle = "Payers",
    sharesTitle = "Shares",
    paidHowMuchLabel = "How much did they pay?",
    paidHowMuchHint = "How much did this member pay out of pocket?",
    payFullAmountLabel = "Mark as full payer",
    clearAmountLabel = "Clear amount",
    baseShareLabel = "This member's base share",
    shareAmountHint = "How much of the expense belongs to this member?",
    equalBaseShareLabel = "Equal base share",
    expenseSummaryTitle = "Live expense summary",
    enteredPayersTitle = "Entered payers",
    remainingPayersTitle = "Remaining payer amount",
    enteredSharesTitle = "Entered shares",
    remainingSharesTitle = "Remaining share amount",
    finalSharesTitle = "Final share total",
    payerRemainingHintLabel = "Remaining to pay",
    shareRemainingHintLabel = "Remaining share",
    taxToggleTitle = "This expense includes tax or service",
    taxToggleSubtitle = "Useful for restaurant service, tax, or extra percentage fees.",
    taxPercentLabel = "Tax percent",
    taxAmountLabel = "Tax amount",
    taxBreakdownTitle = "Tax breakdown",
    baseAmountLabel = "Base amount",
    taxShareLabel = "This member's tax",
    serviceChargeShareLabel = "This member's extra service",
    finalShareLabel = "Final share",
    showDetailsLabel = "Details",
    hideDetailsLabel = "Hide details",
    serviceChargesTitle = "Extra services",
    serviceChargesSubtitle = "For fixed fees like table service or special service charges.",
    addServiceChargeLabel = "Add service",
    serviceChargeNameLabel = "Service name",
    serviceChargeAmountLabel = "Service amount",
    serviceChargeMembersLabel = "Who is this for?",
    serviceChargeHint = "Choose an amount and the related members for this service.",
    serviceChargesTotalLabel = "Extra services total",
    completeExpenseForm = "Complete form",
    calculatorTitle = "Calculator",
    calculatorExpressionLabel = "Expression",
    calculatorInvalidExpression = "Expression is not valid",
    calculatorUseAction = "Use amount",
    creditorLabel = "Creditor",
    debtorLabel = "Debtor",
    settledLabel = "Settled",
    paidStat = "Paid",
    owedStat = "Owed",
    netStat = "Net",
    edit = "Edit",
    delete = "Delete",
    back = "Back",
    settingsHeroTitle = "Tune the app language and look",
    settingsHeroSubtitle = "Switch between Persian and English, and between light and dark themes.",
    accountTitle = "Account",
    accountSubtitleGuest = "You are in guest mode. Sign in to enable sync.",
    accountSubtitleSignedIn = "The active identity used for syncing data.",
    syncTitle = "Sync",
    syncSubtitle = "Check connection health, last sync time, and trigger a manual sync.",
    syncOnline = "Online",
    syncOffline = "Offline",
    syncLoginRequired = "Sign in to use sync.",
    syncNow = "Instant sync",
    syncInProgress = "Syncing...",
    lastSyncPrefix = "Last sync:",
    notSyncedYet = "Not synced yet",
    syncConnectionIssue = "No internet connection. Try again when you're back online.",
    syncServerIssue = "Sync did not complete. Please try again in a moment.",
    logoutLabel = "Sign out",
    signInLabel = "Sign in",
    languageTitle = "Language",
    languageSubtitle = "Choose the app language and layout direction.",
    themeTitle = "Theme",
    themeSubtitle = "Pick the appearance that feels best for daily use.",
    persianLabel = "فارسی",
    englishLabel = "English",
    lightLabel = "Light",
    darkLabel = "Dark",
)

val LocalAppStrings = staticCompositionLocalOf { faStrings }
val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.FA }

fun stringsFor(language: AppLanguage): AppStrings = if (language == AppLanguage.EN) enStrings else faStrings

@Composable
fun appStrings(): AppStrings = LocalAppStrings.current

fun resolveUserFacingSyncError(
    rawMessage: String?,
    strings: AppStrings,
): String? {
    if (rawMessage.isNullOrBlank()) return null
    val message = rawMessage.lowercase()
    return when {
        "401" in message ||
            "unauthorized" in message ||
            "invalid token" in message ||
            "refresh token" in message -> strings.syncLoginRequired
        "unable to resolve host" in message ||
            "failed to connect" in message ||
            "timeout" in message ||
            "timed out" in message ||
            "no address associated with hostname" in message ||
            "network" in message ||
            "socket" in message ||
            "connection reset" in message ||
            "unreachable" in message -> strings.syncConnectionIssue
        else -> strings.syncServerIssue
    }
}
