package com.encer.offlinesplitwise.core.common

enum class MessageKey {
    EXPENSE_TOTAL_POSITIVE,
    EXPENSE_AT_LEAST_ONE_PAYER,
    EXPENSE_AT_LEAST_ONE_SHARE,
    EXPENSE_NEGATIVE_VALUES,
    EXPENSE_PAYER_TOTAL_MISMATCH,
    EXPENSE_SHARE_TOTAL_MISMATCH,
    EXPENSE_TITLE_REQUIRED,
    EXPENSE_AMOUNT_TOO_LARGE,
    EXPENSE_SAVED,
    SETTLEMENT_SELECT_TWO_MEMBERS,
    SETTLEMENT_MEMBERS_MUST_DIFFER,
    SETTLEMENT_AMOUNT_POSITIVE,
    SETTLEMENT_AMOUNT_TOO_LARGE,
    SETTLEMENT_SAVED,
}
